<a href="https://colab.research.google.com/github/zilphar/Bike-Purchases/blob/main/PR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import sys
import numpy as np

arr = [2, 3, 4, 6, 1, 7, 8]

print(np.array(arr))

print(arr[2])  # indexing

print(arr[1:])

[2 3 4 6 1 7 8]
4


In [17]:
# changing data type
arr = [2, 3, 4, 6, 1, 7, 8]

print(np.array(arr, dtype = float))


myarray = np.array([[[1, 2, 3, 4,], [2, 8, 0, 4]], [[4, 1, 9, 2], [3, 0, 2, 7]]])

print(myarray)
print(myarray.ndim)

print(myarray[1, 0])  # first element in index one



print(np.arange(6))

a = np.arange(5)
a + 20
print(a)

[2. 3. 4. 6. 1. 7. 8.]
[[[1 2 3 4]
  [2 8 0 4]]

 [[4 1 9 2]
  [3 0 2 7]]]
3
[4 1 9 2]
[0 1 2 3 4 5]
[0 1 2 3 4]


In [12]:
A = np.array([
    ['a', 'b', 'c'],
    ['d', 'e', 'f'],
    ['g', 'h', 'i']
])

print(A[:, :2])

[['a' 'b']
 ['d' 'e']
 ['g' 'h']]


In [2]:
import numpy as np
a = np.arange(5)

print(a <= 3)

[ True  True  True  True False]
